### ISSUE TITLE
Labels to remove in "francois_special_v1"

### ISSUE THREAD

**Issue by robbwh** [MASILab/connectoflow_spider#1]
Hello @frheault or current maintainer,

Currently it looks like slant labels 4 40 41 44 45 51 52 are removed from the connectivity matrix, but I was wondering why the 4th ventricle label #11 was left in? Also the inferior lateral ventricles were left in (#49,#50). Is that on purpose? Forgive the question if it is supposed to be left in. 

We can also just remove it in post-processing if it doesn't impact the processing steps

We are using "francois_special_v1" on XNAT to get DTI connectivity matrices. We get out a 125x125 matrix, similar to this [paper](https://doi.org/10.1117/12.2611845) so it seems like all is well.

I notice a IN_LABELS_TO_REMOVE argument has been added in a recent commit. Should we re-run with a more updated version?

Thank you,
Hudson

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
